### ISSUE TITLE
你好，我在make的时候的问题

### ISSUE THREAD

**Issue by Dyqer** [hurley25/sniffer#1]
cc1plus: out of memory allocating 3355443200 bytes after a total of 462848 bytes

**Comment by hurley25** [comment]
从字面上看是内存不足，不清楚你的情况...

**Comment by camera-haopeng** [comment]
解压缩 Winpcap后应该怎么改INCLUDEPATH ？ qt creator报错说<pcap.h> <remote-ext.h> 找不到

**Comment by hurley25** [comment]
sniffer_win32.pro 编辑这个文件，INCLUDEPATH += D:\xxxx 修改路径就好，或者最简单的方法，你直接把Winpcap解压到代码目录就行了。

**Comment by camera-haopeng** [comment]
我在qt5.4.1下面好像跑不了哦，please，，谢谢

**Comment by hurley25** [comment]
嗯，4.x的Qt写的~5.x需要修改的

**Comment by camera-haopeng** [comment]
好，我直接安装4.x的，具体是4.几的呢？

**Comment by camera-haopeng** [comment]
谢谢了。

**Comment by hurley25** [comment]
4.x 的应该都可以的。

**Comment by camera-haopeng** [comment]
我试了4.8，报错，你用的哪个版本的qt？

**Comment by camera-haopeng** [comment]
error: 'socklen_t' was not declared in this scope  socklen_t sockaddrlen;
  ^
 error: expected ';' before 'sockaddrlen'
  socklen_t sockaddrlen;
            ^
 error: 'A' was not declared in this scope
 A sockaddrlen = sizeof(struct sockaddr_in6);
 ^
error: expected ';' before 'sockaddrlen'
 A sockaddrlen = sizeof(struct sockaddr_in6);
   ^

**Comment by hurley25** [comment]
4.8.5

**Comment by Clinmage** [comment]
大哥，你是用VS写的还是，qt creator写的，我用qt creator编译就会内存超出，请问你的MinGW版本是4.8.x吗

**Comment by Clinmage** [comment]
大哥这个问题解决了吗 ？
cc1plus.exe:-1: error: out of memory allocating 838860800 bytes

**Comment by hurley25** [comment]
个人闹着玩写的东西，很多年前了，不是对外提供服务的，不解决使用或者编译问题
